# Generated by Django 5.2.1 on 2026-02-24 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='match',
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(default='Batsman', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.team'),
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('rank', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
